### ISSUE TITLE
Is that project still alive ?

### ISSUE THREAD

**Issue by Blair2004** [yevgenko/printer-express#1]
I have been looking for such solutions many time before. And i'm suprised that it's not more active, that's why i would like to know if it's still alive ?

**Comment by yevgenko** [comment]
Back in the days there were at least two alternatives:

* https://developers.google.com/cloud-print/
* https://www.printnode.com/en

I think printnode is close to printer-express, but more production ready.

It might take some effort to make printer-express production ready, so, might be good idea to asses viable advantage versus commercially available products.

p.s.
sorry for "bit" later response :)

**Comment by Blair2004** [comment]
Thanks i've build one with some existing nodejs package.
Currently on sale : https://codecanyon.net/item/nexo-print-server/21867974
